Microverse Project Floating and Positioning: New York Times Article Copy
alejandrotoledoweb/nyt-article pull request #2
Opened 2020-09-21 21:25 UTC by Janluc

## New York Times Article Clone
- Used Float, Grid, and Flexbox for the general styling of the page.
- Use of Navbar and Footer
- Use of Article, Sections, and other semantic HTML

2020-09-21 22:44 UTC, kevincappuccino requested changes
# [STATUS] CHANGES REQUIRED♻️


#### Overall the project looks really nice and I can see that you guys are working hard on it, and don't worry, you're almost done, there are just some required changes that you guys have to implement to proceed:


_Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, in order to get more knowledge and have a better project to add at your portfolio.

## [REQUIRED CHANGES]
- [x] Your project's navbar should have an embedded NYT logo and it should be a link.
- [x] At the section "The Theory of Inflation", the image should be only one with text above it. (Just like the original)
- Yours (8 images)
![image](https://user-images.githubusercontent.com/56762529/93828874-ab49c100-fc42-11ea-9de6-08f49500751e.png)
- Original (Only one image)
![image](https://user-images.githubusercontent.com/56762529/93828899-ba307380-fc42-11ea-8efa-545cba73c21d.png)

- [ ] Kindly remember to remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
Take a look at this example:
![image](https://user-images.githubusercontent.com/56762529/90803794-a914df80-e2ef-11ea-9be0-40267c665254.png)
Your HTML will be something like this: 
![image](https://user-images.githubusercontent.com/56762529/90803950-e7120380-e2ef-11ea-8221-5d5d3a13e033.png)
Apply the same logic above in **ALL** those repeated rules listed below:
       7 |   color: black;
       7 |   text-decoration: none;
       6 |   font-size: 12px;
       6 |   margin: 0 auto;
       5 |   color: #666;
       5 |   color: #888;
       5 |   justify-content: space-between;

## [OPTIONAL CHANGES]
- [ ] Please use the images of the actual page, instead of that grey ones;

### Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀

👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question about this review? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

2020-09-21 22:44 UTC, kevincappuccino commented on README.md
>  Additional description about the project and its features.
- [ ] The description is above the image, so you can remove this text.

2020-09-22 13:02 UTC, arslanbisharat requested changes
### Request changes 😳
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet.😟 You need to work more on it. 
_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**

-[ ] Your project's navbar should have an embedded NYT logo and it should be a link.nPlease make the  New York Times logo a link. 

-[ ] In the section "The Theory of Inflation", the image should be only one with text above it. (Just like the original)
-[ ] Your page is not correctly styled. Please work on it.

![chrome-capture (15)](https://user-images.githubusercontent.com/58504655/93885430-8f572580-fcfd-11ea-9b16-7c4540498952.jpg)



**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-09-22 16:24 UTC, jubaan requested changes
# Status: Changes Required :recycle:

## Awesome work guys! :clap: :clap: :clap:

:100: The sites looks very close to the original!
:100: Using semantic HTML
:100: Great improvement with the applied changes

You're almost there, please work on the issues below:

## Required Changes
### [Mandatory]

- [ ] NewYorkTime logo not centered
![image](https://user-images.githubusercontent.com/25774518/93907415-eb508880-fcc2-11ea-943d-cdb1231159e4.png)

- [ ] Section not displaying correctly
![image](https://user-images.githubusercontent.com/25774518/93907574-1fc44480-fcc3-11ea-8965-5f209127b311.png)

- [ ] **Outdated link to live preview. Fixing this should solve the issues above.**

- [ ] Issue, MIT licence links broken.
![image](https://user-images.githubusercontent.com/25774518/93908542-62d2e780-fcc4-11ea-8409-12fa56d13468.png)

- [ ] ```footer``` should be outside the ```main``` tag.

### [OPTIONAL]

- [ ] Images not showing. Try to make the project looks as similar as possible. This is a great mockup but the project should be a clone.
![image](https://user-images.githubusercontent.com/25774518/93907509-07ecc080-fcc3-11ea-90da-1b98fa9770e9.png)
![image](https://user-images.githubusercontent.com/25774518/93908216-0079e700-fcc4-11ea-9a23-64ef26cbdfdb.png)
![image](https://user-images.githubusercontent.com/25774518/93908256-096ab880-fcc4-11ea-8aed-2842403478c0.png)

2020-09-22 17:14 UTC, jubaan requested changes
# Status: Changes Required :recycle:

## :wave: Hi guys! 

Please ensure the project pass all linter checks before submitting a re-review.

- [ ] Project not passing all linters check.

2020-09-22 17:38 UTC, jubaan approved these changes
# Status: Approved :tada: :tada: :tada:

## Congrats team!! you've worked on all required changes!

You may now merge to master!

## :fireworks: Well done!

2020-09-22 17:45 UTC, merged